# Databricks notebook source
# MAGIC %md
# MAGIC ![databricks_academy_logo.png](./Includes/images/databricks_academy_logo.png "databricks_academy_logo.png")

# COMMAND ----------

# MAGIC %md
# MAGIC # Prompt Engineering Basics
# MAGIC - **Prompt**: An AI prompt is an input or query given to a large language model to elicit a specific response or output.
# MAGIC
# MAGIC - **Prompt Engineering**: The practice of designing and refining prompts to optimize the responses generated by AI models

# COMMAND ----------

# MAGIC %md
# MAGIC ## Prompt Basics
# MAGIC ![prompt-example.png](./Includes/images/prompt-example.png "prompt-example.png")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Tip: Prompts are model-specific
# MAGIC - Different models may require different prompts.
# MAGIC
# MAGIC - Provide examples and cues to guide model’s response generation.  
# MAGIC
# MAGIC - Different use cases may require different prompts techniques.
# MAGIC
# MAGIC   >Example: Classification task vs. translation
# MAGIC
# MAGIC - Iterative development is key.
# MAGIC
# MAGIC   >Iterate by adjusting the temperature parameter—higher for more creative outputs, lower for focused responses.
# MAGIC
# MAGIC - Be aware of biased responses. 
# MAGIC
# MAGIC - Check for hallucinations and inaccurate information.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Tip: Format prompts
# MAGIC ![format-prompts.png](./Includes/images/format-prompts.png "format-prompts.png")
# MAGIC
# MAGIC - Use delimiters to distinguish between instruction and context 
# MAGIC     - Pound sign ### 
# MAGIC     - Backticks ```
# MAGIC     - Braces / brackets {} / [] 
# MAGIC     - Dashes --- 
# MAGIC
# MAGIC - Ask the model to return structured output
# MAGIC     - HTML, json, table, markdown, etc. 
# MAGIC
# MAGIC - Provide a correct example
# MAGIC     - "Return the movie name mentioned in the form of a Python dictionary. The output should look like {'Title': 'In and Out'}"
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## Tip: Guide the model for better responses
# MAGIC
# MAGIC - Ask the model not to make things up/hallucinate
# MAGIC     - "Do not make things up if you do not know. Say 'I do not have that information'"
# MAGIC
# MAGIC
# MAGIC - Ask the model not to assume or probe for sensitive information
# MAGIC     - "Do not make assumptions based on nationalities" 
# MAGIC     - "Do not ask the user to provide their SSNs" 
# MAGIC
# MAGIC
# MAGIC - Ask the model not to rush to a solution
# MAGIC     - Ask it to take more time to “think” or ask to follow step-by-step approach
# MAGIC     - "Explain how you solve this math problem" 
# MAGIC     - "Do this step-by-step. Step 1: Summarize into 100 words.
# MAGIC      - Step 2: Translate from English to French..."
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## Benefits and Limitations of Prompt Engineering
# MAGIC - Benefits:
# MAGIC     - **Simple and efficient**: The time taken to generate the ideal results is significantly low.
# MAGIC     - **Predictable results**: Consistently generate results that meet predefined standards for accuracy.
# MAGIC     - **Tailored outputs**: Customization of AI responses to fit specific needs or styles.
# MAGIC
# MAGIC - Limitations:
# MAGIC     - The output depends on used model.
# MAGIC     - Limited by pre-trained model's internal knowledge. **For external knowledge we need to provide extra contextual information**. 
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC &copy; 2026 Databricks, Inc. All rights reserved. Apache, Apache Spark, Spark, the Spark Logo, Apache Iceberg, Iceberg, and the Apache Iceberg logo are trademarks of the <a href="https://www.apache.org/" target="_blank">Apache Software Foundation</a>.<br/><br/><a href="https://databricks.com/privacy-policy" target="_blank">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use" target="_blank">Terms of Use</a> | <a href="https://help.databricks.com/" target="_blank">Support</a>