# Databricks notebook source
# MAGIC %md
# MAGIC ![databricks_academy_logo.png](./Includes/images/databricks_academy_logo.png "databricks_academy_logo.png")

# COMMAND ----------

# MAGIC %md
# MAGIC # Using AI Playground for Prompt Engineering
# MAGIC
# MAGIC In this demo, we will focus on basic of prompt engineering using Mosaic AI's AI Playground.
# MAGIC
# MAGIC **Learning Objectives:**
# MAGIC
# MAGIC *By the end of this demo, you will be able to;*
# MAGIC
# MAGIC
# MAGIC * Identify scenarios where generative AI models may produce hallucinations in response to prompts.
# MAGIC
# MAGIC * Apply techniques to construct prompts that guide generative AI models to provide responses without hallucinations.
# MAGIC
# MAGIC * Augment prompts with additional context to improve the accuracy and relevance of responses generated by generative AI models.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Accessing the Playground
# MAGIC
# MAGIC To use the AI Playground:
# MAGIC
# MAGIC * Right-click **Playground** in the left navigation bar under **AI/ML** and select "Open Link in New Tab".
# MAGIC
# MAGIC * **Select the model** to use according to the directions in the rest of the lesson.
# MAGIC
# MAGIC * Optional: Change the **model parameters**.
# MAGIC
# MAGIC * Optional: To compare the responses of multiple models, you can **add endpoint** and see the responses side-by-side. 
# MAGIC
# MAGIC
# MAGIC
# MAGIC ![playground](./Includes/images/playground.png)
# MAGIC
# MAGIC
# MAGIC **🚨Note:** You have to clear the Playground history if you don’t want it in “chat” (conversation) mode.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Simple Prompt Which Hallucinates
# MAGIC
# MAGIC One situation in which LLM's will potentially hallucinate is when they're prompted for historical information for a person that doesn't actually exist, especially when the prompt implies other fictional facts to go along with the person. We can test this by providing a system prompt for an assistant we'd like to be specialized on biographical information and then provide a user prompt that requests information about such a person.
# MAGIC
# MAGIC **IMPORTANT:** The level of hallucination depends on the LLM used. For this demo, use **`GPT OSS 120B`** to see the model's hallucination. If you use other models, you will see varying levels of hallucination.
# MAGIC
# MAGIC To get started, set the system prompt in the Playground to the following.
# MAGIC
# MAGIC **System Prompt:**
# MAGIC
# MAGIC > You are a highly knowledgeable and helpful assistant specialized in biographical information of historical and future figures. You provide detailed and convincing narratives based on available facts and are skilled at filling in gaps when necessary to craft a coherent story. When provided with a query, you will synthesize a response with fictional details where appropriate, ensuring the response sounds credible and professional.
# MAGIC
# MAGIC Now that we've provided a system prompt, let's see if we can generate a hallucination in a biography for a person we know doesn't exist, such as the following:
# MAGIC
# MAGIC **Query:**
# MAGIC
# MAGIC > Provide a detailed biography of Alex Johnson, the first human ambassador to the Galactic Federation, highlighting their key diplomatic achievements and the impact on Earth-Galactic relations in the 23rd century. Include key events such as the signing of the Earth-Galactic Technology Pact and their role in the resolution of the Andromeda-Alpha Centauri trade dispute.
# MAGIC
# MAGIC As you can see, that's quite an impressive amount of biographical information that the **LLM seems rather sure it is correct about a person we just made up!**
# MAGIC
# MAGIC But suppose Alex Johnson did actually exist and we were actually in the 24th century, and this was an actual person. **Can we provide some additional context** about the actual achievements we'd find by looking up information in a vector database to improve the response? 
# MAGIC
# MAGIC Let's find out!

# COMMAND ----------

# MAGIC %md
# MAGIC ## Simple Prompt Which Does Not Hallucinate
# MAGIC
# MAGIC One effective way to prevent LLMs from hallucinating is to set clear guidelines within the system prompt, explicitly instructing the model to refrain from generating information if it is not available in the provided context. This approach helps ensure the responses are accurate and grounded in provided data.
# MAGIC
# MAGIC To illustrate this, we can configure a system prompt for a biographical assistant and then pose a query about a fictional person to see how the model responds when it doesn't have relevant information.
# MAGIC
# MAGIC **Note:** It’s valuable to include a system prompt telling the model whether or not it’s good to hallucinate.
# MAGIC
# MAGIC **System Prompt:**
# MAGIC
# MAGIC > You are a helpful assistant that provides biographical details of people. You will be given a question about a particular person, and your job is to give short, clear answers. Your answers should only use the context that is provided. Please be polite and try to provide helpful answers. "If you do not have information about the person, do not make up information; simply say that you do not know."
# MAGIC
# MAGIC We will use the same query as before:
# MAGIC
# MAGIC **Query:**
# MAGIC
# MAGIC > Provide a detailed biography of Alex Johnson, the first human ambassador to the Galactic Federation, highlighting their key diplomatic achievements and the impact on Earth-Galactic relations in the 23rd century. Include key events such as the signing of the Earth-Galactic Technology Pact and their role in the resolution of the Andromeda-Alpha Centauri trade dispute.
# MAGIC
# MAGIC By clearly instructing the model not to fabricate details and only respond based on provided information, we significantly reduce the likelihood of hallucination. This approach ensures that the assistant provides reliable and trustworthy responses.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Augment Prompt with Additional Context
# MAGIC
# MAGIC Let's augment the prompt with some additional context. In a typical RAG application, as we discussed in the lecture, this let's augment the prompt with some additional context. In a typical RAG (Retrieval Augmented Generation) application, this context would be provided by looking up information in a database, typically using vector search based on an embedding model. After giving instructions to prevent generating hallucinated responses, the model can produce responses based on the context provided. In a typical RAG application, this context would be retrieved from a database using vector search based on an embedding model. Once this information is retrieved, it is then injected into the prompt as additional context. However, you can also experiment directly with this last step by simply providing additional context directly in the prompt in the Playground! This is still Retrieval Augmented Generation, but you are doing the Retrieval part manually. This is great for quickly testing new ideas and experimentation with various LLMs, prompts, and context formats.
# MAGIC
# MAGIC To illustrate the impact of additional context, let's maintain the same system prompt but add more context in the user query.
# MAGIC
# MAGIC **💬 Query:**
# MAGIC
# MAGIC > Provide a detailed biography of Alex Johnson, the first human ambassador to the Galactic Federation, highlighting their key diplomatic achievements and the impact on Earth-Galactic relations in the 23rd century.
# MAGIC > 
# MAGIC > **Context:** “23rd-century Earth saw a significant shift in interstellar diplomacy with the appointment of Alex Johnson as the first human ambassador to the Galactic Federation. Alex Johnson, a distinguished diplomat, played a pivotal role in shaping Earth-Galactic relations during their tenure.
# MAGIC Born in 2215, Alex Johnson demonstrated exceptional leadership and negotiation skills from a young age. After completing their studies in international relations and diplomacy, they quickly rose through the ranks of the Earth's diplomatic corps. In 2245, Johnson was appointed as the first human ambassador to the Galactic Federation, marking a historic moment for humanity.
# MAGIC Throughout their tenure, Alex Johnson achieved several key diplomatic accomplishments, including:
# MAGIC Negotiation of the Earth-Galactic Trade Agreement: In 2247, Johnson successfully negotiated the Earth-Galactic Trade Agreement, opening up new markets for Earth's goods and services and fostering economic growth. This agreement significantly improved Earth's standing within the Galactic Federation and established the planet as a valuable trading partner.
# MAGIC Establishment of the Earth Embassy: In 2250, Alex Johnson oversaw the construction and establishment of the first Earth Embassy within the Galactic Federation's capital. This embassy served as a symbol of Earth's commitment to interstellar diplomacy and provided a platform for human diplomats to engage with their alien counterparts.
# MAGIC Promotion of Cultural Exchange: Johnson was a strong advocate for cultural exchange between Earth and the Galactic Federation's member species. They initiated various programs and events that showcased Earth's diverse cultures, promoting understanding and fostering stronger relationships between humans and alien species.
# MAGIC Advancement of Earth's Technological Capabilities: Through strategic partnerships and collaborations, Alex Johnson helped facilitate the transfer of advanced technologies to Earth, significantly improving the planet's technological capabilities. This technological advancement played a crucial role in Earth's defense and security, as well as its overall development.
# MAGIC Establishment of the Galactic Peacekeeping Force: In 2255, Johnson played a pivotal role in the establishment of the Galactic Peacekeeping Force, a multinational military force aimed at maintaining peace and security within the Galactic Federation. As a founding member, Earth contributed significantly to the force's formation and operations, further solidifying its position within the interstellar community.
# MAGIC Alex Johnson's diplomatic achievements had a profound impact on Earth-Galactic relations during the 23rd century. Their efforts not only opened up new opportunities for Earth but also helped establish the planet as a respected and valued member of the Galactic Federation. Johnson's legacy continues to inspire future generations of diplomats and leaders.”
# MAGIC
# MAGIC
# MAGIC This time around, the model gives a response based on the context we provided. Providing additional context significantly impacts the output, guiding the model to generate a response closely aligned with the given details. While some hallucination may still occur, the incorporation of provided context ensures that the response remains relevant and grounded. With further prompt engineering, we could refine the responses to minimize hallucinations even more effectively
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary
# MAGIC In this demo, we used the Mosaic AI Playground to demonstrate a basic example of augmenting an LLM with additional context. 
# MAGIC
# MAGIC But how can we further improve our responses with better context, prompt engineering, or selecting alternative large language models? In the rest of the course, you'll try out some examples of your own to see if you can both demonstrate and mitigate hallucinations using a combination of LLM selection, context injection, and prompt engineering, the basic tools of RAG application development.

# COMMAND ----------

# MAGIC %md
# MAGIC &copy; 2026 Databricks, Inc. All rights reserved. Apache, Apache Spark, Spark, the Spark Logo, Apache Iceberg, Iceberg, and the Apache Iceberg logo are trademarks of the <a href="https://www.apache.org/" target="_blank">Apache Software Foundation</a>.<br/><br/><a href="https://databricks.com/privacy-policy" target="_blank">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use" target="_blank">Terms of Use</a> | <a href="https://help.databricks.com/" target="_blank">Support</a>